Update jen-op-2133506a

diff --git a/jen-op-2133506a b/jen-op-2133506a
--- a/jen-op-2133506a
+++ b/jen-op-2133506a
@@ -8,9 +8,11 @@ pipeline {
             steps {
                 script {
                     echo "Op-2133506a-S1: QA web server is backup and updated"
-                    sh 'docker rmi -f qa-bkup-image || true'
-                    sh 'docker commit 2133506a-qa-svr qa-bkup-image'
-                    sh 'bolt script run /operate/2133506a/2133506a.script -t docker://2133506a-qa-svr'
+                    sh '''
+                        docker rmi -f qa-bkup-image || true
+                        docker commit 2133506a-qa-svr qa-bkup-image
+                        /usr/bin/bolt script run /operate/2133506a/2133506a.script --targets 2133506a-qa-svr.localdomain --no-host-key-check
+                    '''
                 }
             }
         }
@@ -18,9 +20,11 @@ pipeline {
         stage('Op-2133506a-S2') {
             steps {
                 script {
-                    echo "Op-2133506a-S2: Checking QA server after update"
-                    sh 'curl -Is http://localhost:33200 | head -n 1 > /tmp/qa-result-file'
-                    sh 'cat /tmp/qa-result-file'
+                    echo "Op-2133506a-S2: Checking on whether QA server is running after update"
+                    sh '''
+                        curl -Is http://localhost:33200 | head -n 1 > /tmp/qa-result-file
+                        cat /tmp/qa-result-file
+                    '''
                 }
             }
         }
@@ -30,21 +34,15 @@ pipeline {
                 script {
                     def qaStatus = sh(script: 'curl -s -o /dev/null -w "%{http_code}" http://localhost:33200', returnStdout: true).trim()
                     if (qaStatus == "200") {
-                        echo "Op-2133506a-S3: Proceed to approval step"
+                        echo "Op-2133506a-S3: Proceed to roll out to Prod server"
                     } else {
-                        echo "Op-2133506a-S3: QA server rolled back"
-                        sh 'docker stop 2133506a-qa-svr && docker rm 2133506a-qa-svr'
-                        sh 'docker run -d --name 2133506a-qa-svr -p 33200:80 qa-bkup-image'
+                        echo "Op-2133506a-S3: QA server fails after update and is rolled back"
+                        sh '''
+                            docker stop 2133506a-qa-svr && docker rm 2133506a-qa-svr
+                            docker run -d --name 2133506a-qa-svr -p 33200:80 qa-bkup-image
+                        '''
                         error('Aborting')
                     }
-                }
-            }
-        }
-
-        stage('Op-2133506a-Approval') {
-            steps {
-                script {
-                    input(message: 'QA passed. Approve deployment to Prod?', ok: 'Deploy')
                 }
             }
         }
@@ -53,9 +51,11 @@ pipeline {
             steps {
                 script {
                     echo "Op-2133506a-S4: PROD web server is backup and updated"
-                    sh 'docker rmi -f prod-bkup-image || true'
-                    sh 'docker commit 2133506a-prod-svr prod-bkup-image'
-                    sh 'bolt script run /operate/2133506a/2133506a.script -t docker://2133506a-prod-svr'
+                    sh '''
+                        docker rmi -f prod-bkup-image || true
+                        docker commit 2133506a-prod-svr prod-bkup-image
+                        /usr/bin/bolt script run /operate/2133506a/2133506a.script --targets 2133506a-prod-svr.localdomain --no-host-key-check
+                    '''
                 }
             }
         }
@@ -63,9 +63,11 @@ pipeline {
         stage('Op-2133506a-S5') {
             steps {
                 script {
-                    echo "Op-2133506a-S5: Checking Prod server after update"
-                    sh 'curl -Is http://localhost:33500 | head -n 1 > /tmp/prod-result-file'
-                    sh 'cat /tmp/prod-result-file'
+                    echo "Op-2133506a-S5: Checking on whether Prod server is running after update"
+                    sh '''
+                        curl -Is http://localhost:33500 | head -n 1 > /tmp/prod-result-file
+                        cat /tmp/prod-result-file
+                    '''
                 }
             }
         }
@@ -75,11 +77,13 @@ pipeline {
                 script {
                     def prodStatus = sh(script: 'curl -s -o /dev/null -w "%{http_code}" http://localhost:33500', returnStdout: true).trim()
                     if (prodStatus == "200") {
-                        echo "Op-2133506a-S6: Release to production"
+                        echo "Op-2133506a-S6: Proceed to release Prod web server to production"
                     } else {
-                        echo "Op-2133506a-S6: Prod server rolled back"
-                        sh 'docker stop 2133506a-prod-svr && docker rm 2133506a-prod-svr'
-                        sh 'docker run -d --name 2133506a-prod-svr -p 33500:80 prod-bkup-image'
+                        echo "Op-2133506a-S6: Prod web server is rolled back"
+                        sh '''
+                            docker stop 2133506a-prod-svr && docker rm 2133506a-prod-svr
+                            docker run -d --name 2133506a-prod-svr -p 33500:80 prod-bkup-image
+                        '''
                         error('Aborting')
                     }
                 }
@@ -88,7 +92,7 @@ pipeline {
         
         stage('Op-2133506a-S7') {
             steps {
-                echo "Op-2133506a-S7: Prod server ready to serve."
+                echo "Op-2133506a-S7: Prod web server is monitored and ready to serve."
             }
         }
     }
